### PR TITLE
Add Instructions for theme

### PR DESCRIPTION
**Pull request by 0oAstro**
My fav search engine with my fav theme 😄

### CODE REVIEW

**Comment by esdmr** [comment]
Although passphrases work, they are not intended to be shared. It is possible to change or even delete[^1] that passphrase.

~~Instead, it is possible to share a “Bookmarklet URL”. See <https://duckduckgo.com/params> for reference. It is also available using “Show Bookmarklet and Settings Data” in the settings. (It is the normal bookmarklet, not “Cloud Save Bookmarklet URL”.)~~

Edit: Seems that URL parameters are not persistent. Maybe a script which sets up cookies would work? 

[^1]: From DuckDuckGo help page [“Cloud Save”](https://help.duckduckgo.com/duckduckgo-help-pages/settings/cloud-save/) §&nbsp;“How do I change my passphrase?”

**Comment by DonutDev** [comment]
the passphrase no longer works

**Comment by 0oAstro** [comment]
> the passphrase no longer works

well it seems to work for me, just checked `catppuccin-ddg`

**Comment by 0oAstro** [comment]
> Although passphrases work, they are not intended to be shared. It is possible to change or even delete[1](#user-content-fn-1-ce060ddaa3db01057745c7082dd6ee9b) that passphrase.
> 
> ~Instead, it is possible to share a “Bookmarklet URL”. See [duckduckgo.com/params](https://duckduckgo.com/params) for reference. It is also available using “Show Bookmarklet and Settings Data” in the settings. (It is the normal bookmarklet, not “Cloud Save Bookmarklet URL”.)~
> 
> Edit: Seems that URL parameters are not persistent. Maybe a script which sets up cookies would work?
> 
> ## Footnotes
> 1. From DuckDuckGo help page [“Cloud Save”](https://help.duckduckgo.com/duckduckgo-help-pages/settings/cloud-save/) § “How do I change my passphrase?” [leftwards_arrow_with_hook](#user-content-fnref-1-ce060ddaa3db01057745c7082dd6ee9b)

seems like a nice plan to use script, also we can use stylus and style sheets

**Comment by esdmr** [comment]
Since there was a bookmarklet, I restored the passphrase (for how long it will last).

Here is a script which installs the cookies:

```js
const maxAge = 4 * 365 * 24 * 60 * 60;
const theme = [
	'1=-1', '18=1', 'a=-1', 'ae=d', 'ao=-1', 'ap=-1', 'aq=-1', 'au=-1',
	'ax=-1', 'bc=1', 'l=wt-wt', 's=m', '21=332E41', '7=1E1E29', '8=C3BAC6',
	'9=A4B9EF', 'aa=BEE4ED', 'j=1B1923', 'x=A4B9EF',
];

for (const item of theme) {
	document.cookie = `${item}; max-age=${maxAge}; samesite=lax; secure`;
}
```

Also, here is a [userscript](https://gist.githubusercontent.com/esdmr/015cdb5750ae87b1edc1115da772e194/raw/8bcfdedb9de09db67a6dca3dfc6205ddf729eafc/catppuccin-ddg.user.js) for those who prefer it.

**Pull request closed without merging**
