### PR TITLE
feat: create a userstyle

### PR DESCRIPTION
**Pull request by rubyowo**

### CODE REVIEW

**Comment by rubyowo** [comment]
Closes #7

**Comment by PoorPocketsMcNewHold** [comment]
Screenshot 2023-08-26 at 12-19-51 Catppuccin at DuckDuckGo
First, the two black gradient on the search options at the top.
```css
       .search-filters-wrap::before,.search-filters-wrap::after {
            background-image:none;
        }
```
image
Second, the visited/un-visited icons on the left. No idea how to theme those. The Visited link one especially blend with the background which is an issue. The class names are randomly generated for each link instead of relying it seems to a visited/un-visited one.
image
The carousel background color were unthemed. I didn't thought they needed to have a distinctive color, as the shadow did their job, but that's just my thought.
```css
       .module:not(.module--carousel):not(.module--placeholder):not(.module--images):not(.module--translations):not(.module__chromeless), .modal--popout .modal__box, .modal__box, .sidebar-modules .module, .results--main .result:not(.result--ad).highlight, .module .module--carousel__item, .user-loc-cta, .address-detail, .modal--dropdown.modal--popout .modal__box, .tile--info, .place-detail, .badge-link, .is-atb-fullbleed .content-info__item, .atb-banner__bottom, .multi-step-mobile-onboarding__step__content, .is-mobile .results_links_deep, .is-mobile .results_links, .is-mobile .result--news, .is-mobile .related-searches, html[data-ntp-features*="tracker-stats-widget:off"] .most-visited__info-tt, .user-loc-tooltip, .anomaly-modal__modal {
            background-color: @base;
        }
```
image
The footer then, with the background footer first.
```css
        .footer, 
        .footer--mobile {
            background-color: @surface0;
            border-color: @surface0;
        }
```
and the buttons/cards
```css
        .footer__card {
            background-color:@base !important;
        }
```
image
Themed the share your feedback little button at the bottom right.
```css
.btn.feedback-btn, .btn.feedback-btn a, .feedback-modal__submit.is-disabled, .feedback-modal__submit.is-disabled:hover, .feedback-modal__submit.is-disabled:active, .feedback-modal__submit.is-disabled:focus, .feedback-single-place-modal__disclaimer, .feedback-prompt, .feedback-prompt__link, .feedback-prompt__link:visited, .products-carousel.has-grid .module--carousel__main-source a, .products-carousel.has-grid .module--carousel__main-source a:visited, .module--carousel .module--carousel__main-source .js-badge--ad, .module--carousel .badge--ad-wrap--product-carousel .js-badge--ad, .module__more-at-and-feedback .module__more-at a, .btn.btn--skeleton, .btn.btn--skeleton:hover, .btn.is-disabled, .btn.is-disabled:hover{
            background-color:@base;
            color:@text;
        }
```
image

**Comment by rubyowo** [comment]
epic. mind converting it into a PR and PR it into my repo?

**Comment by nekowinston** [comment]
See catppuccin/userstyles#486

**Pull request closed without merging**
